apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: grafana/grafana:latest
          ports:
            - containerPort: 3000


apiVersion: v1
kind: Service
metadata:
  name: grafana-service
spec:
  type: NodePort
  ports:
    - port: 3000       # Port exposed on the service
      targetPort: 3000 # Port to which the service should forward traffic inside the pod
      nodePort: 32000 # Port accessible externally on each Node
  selector:
    app: grafana # Label selector to match pods created by your deployment
