apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influx2
  template:
    metadata:
      labels:
        app: influx2
    spec:
      containers:
        - name: influx2
          image: influxdb:latest
          ports:
            - containerPort: 8086




apiVersion: v1
kind: Service
metadata:
  name: influxdb-service
spec:
  type: NodePort
  ports:
    - port: 8086       # Port exposed on the service
      targetPort: 8086 # Port to which the service should forward traffic inside the pod
      nodePort: 32002 # Port accessible externally on each Node
  selector:
    app: influx2 # Label selector to match pods created by your deployment
